language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - '$HOME/.npm'

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

before_install:
  - npm config set loglevel warn

install: npm ci

script:
  - npm test
